name: boty_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  audioplayers: ^5.2.1
  video_player: ^2.8.1
  chewie: ^1.7.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  http_parser: ^4.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
